# Site
name: 'Testing Education Center'
description: 'Testingvn.com is forum for tester'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/home'
disqus: 'Automation Receipts'
email: 'ha.dothanh2011@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Ha
      site:           https://cuhavp.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Ha, the author of Tvn education center site, the theme you're currently previewing. I hope you like it!"
      email:          ha.dothanh2011@gmail.com
      twitter:        https://twitter.com/dothanh2011
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]