# Site
name: 'Software Testing Training Center'
description: 'Testingvn.com is forum for tester'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://cuhavp.github.io'
disqus: 'Automation Receipts'
email: 'ha.dothanh2011@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-pdf-embed

  
authors:
    ha:
      name:           Ha Do
      site:           https://cuhavp.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Ha, the author of Tvn education center site"
      email:          ha.dothanh2011@gmail.com
      twitter:        https://twitter.com/dothanh2011
    thinh:
      name:           Thinh Tran
      site:           ''
      avatar:         /assets/images/avatar4.png
      bio:            "Hi, I am Thinh, the author of Tvn education center site"
      email:          ''
      twitter:        '' 
    suong:
      name:           Suong Bui
      site:           ''
      avatar:         /assets/images/avatar2.jpg
      bio:            "Hi, I am Suong, the author of Tvn education center site"
      email:          ''
      twitter:        '' 
    an:
      name:           An Vo
      site:           ''
      avatar:         /assets/images/avatar2.jpg
      bio:            "Hi, I am An, the author of Tvn education center site"
      email:          ''
      twitter:        ''   
    son:
      name:           Son Hoang
      site:           ''
      avatar:         /assets/images/avatar5.png
      bio:            "Hi, I am Son, the author of Tvn education center site"
      email:          ''
      twitter:        ''
    vu:
      name:           Vu Tran
      site:           ''
      avatar:         /assets/images/avatar6.png
      bio:            "Hi, I am Vu, the author of Tvn education center site"
      email:          ''
      twitter:        ''      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]